-- Expandir tabla hr_employee_costs con campos detallados de nómina
ALTER TABLE hr_employee_costs
  ADD COLUMN IF NOT EXISTS sal_neto DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS total_tc1 DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS irpf_dinero DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS irpf_especie DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS ss_trabajador DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS ss_empresa DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS anticipos DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS embargos DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS dto_preaviso DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS dtos_varios DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS prestamos DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS dto_especial DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS indemnizacion DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS enf_acc DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS bonificacion DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS porcentaje_imputacion DECIMAL(5,2) DEFAULT 100.00;